In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np
data = pd.read_csv("/content/drive/MyDrive/IBM/dataset of day 6 of startsups/50_Startups (1).csv")
data

     R&D Spend  Administration  Marketing Spend       State     Profit
0    165349.20       136897.80        471784.10    New York  192261.83
1    162597.70       151377.59        443898.53  California  191792.06
2    153441.51       101145.55        407934.54     Florida  191050.39
3    144372.41       118671.85        383199.62    New York  182901.99
4    142107.34        91391.77        366168.42     Florida  166187.94
..         ...             ...              ...         ...        ...
103  119943.24       156547.42        256512.92     Florida  132602.65
104  114523.61       122616.84        261776.23    New York  129917.04
105   78013.11       121597.55        264346.06  California  126992.93
106   94657.16       145077.58        282574.31    New York  125370.37
107   91749.16       114175.79        294919.57     Florida  124266.90

[108 rows x 5 columns]

In [3]:
data.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
# Check the missing values in the dataset
data.isnull().sum()
## There is no outliers in this dataset

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [5]:
data.describe()

           R&D Spend  Administration  Marketing Spend         Profit
count     108.000000      108.000000       108.000000     108.000000
mean    74959.338704   121750.788889    214952.664722  113523.760000
std     44996.368152    27322.385654    117937.942120   38991.013654
min         0.000000    51283.140000         0.000000   14681.400000
25%     38558.510000   105077.645000    134050.070000   90708.190000
50%     75791.365000   122699.795000    239452.750000  109543.120000
75%    101913.080000   145077.580000    298664.470000  141585.520000
max    165349.200000   182645.560000    471784.100000  192261.830000

### There is no Missing values

### Then there is no outliers 

###Then we need to do encoding

#ENCODING


## In encoding we need to convert the categorical data into numerica data or binary form.

In [6]:
# In one hot encoding the columns get inceased so we go with label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['State']=le.fit_transform(data['State'])
data.head()
# Now the state categorical data convert into numeric data

   R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

##After encoding seperate the independent and dependent value

In [23]:
y=data['Profit']
x=data.drop(columns=['Profit'],axis=1)

##Next we need to scale the data so the datA IS CONVERTED INTO ARRAY

In [8]:
names=x.columns
names

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State'], dtype='object')

##APPLYING SCALING FUNCTION

In [9]:
from sklearn.preprocessing import scale
x=scale(x)
x
# Now the dataset is converted into an array . see the output.

array([[ 2.01819092,  0.55696553,  2.18783528,  1.16731536],
       [ 1.95675646,  1.0893969 ,  1.95029024, -1.23401909],
       [ 1.75232048, -0.75766814,  1.64392865, -0.03335187],
       [ 1.54982902, -0.1132146 ,  1.43322263,  1.16731536],
       [ 1.49925539, -1.11632102,  1.28814125, -0.03335187],
       [ 1.27083396, -0.806604  ,  1.25996984,  1.16731536],
       [ 1.3319795 ,  0.93574262, -0.74312422, -1.23401909],
       [ 1.23558377,  0.87437939,  0.92787631, -0.03335187],
       [ 1.01776417,  0.99163696,  0.82340982,  1.16731536],
       [ 1.08011094, -0.48065199,  0.76691751, -1.23401909],
       [ 0.60181303, -0.4102384 ,  0.1210342 , -0.03335187],
       [ 0.57410176, -1.10165542,  0.29637694, -1.23401909],
       [ 0.4220906 ,  0.20479752,  0.29718526, -0.03335187],
       [ 0.38030758,  0.50538623,  0.32125438, -1.23401909],
       [ 1.00438367,  1.27949493,  0.35403374, -0.03335187],
       [ 0.88337621,  0.03184527,  0.39886959,  1.16731536],
       [ 0.06818346, -0.00563469,  0.42076085, -1.23401909],
       [ 0.43980557,  0.8577414 ,  0.57603938,  1.16731536],
       [ 0.37487683, -0.27853767,  0.68120328, -0.03335187],
       [ 0.25588265,  1.16795814, -1.83108825,  1.16731536],
       [ 0.02890359, -0.28988105,  0.71310446, -1.23401909],
       [ 0.07658668,  1.1774935 ,  0.72224334,  1.16731536],
       [-0.02154122,  0.03794589,  0.75275659, -0.03335187],
       [-0.165823  , -0.58832162,  0.76510399, -0.03335187],
       [ 0.04654576, -0.82621636, -0.63359259,  1.16731536],
       [-0.22985461,  0.65460485, -0.6558447 , -1.23401909],
       [ 0.00825076,  0.82311815, -0.68917401, -0.03335187],
       [-0.06367255,  0.224807  ,  1.177531  ,  1.16731536],
       [-0.19889043,  2.23914065, -0.82463513, -0.03335187],
       [-0.20884945,  1.15023284, -0.918423  ,  1.16731536],
       [-0.2894745 , -0.22465065, -1.05478086, -0.03335187],
       [-0.30863384,  1.13809338, -1.07959552,  1.16731536],
       [-0.25789476,  0.27463345, -1.43850805, -1.23401909],
       [-0.4346159 , -0.68736485, -0.00270767, -0.03335187],
       [-0.63708012,  1.32165249, -0.03539459, -1.23401909],
       [-0.64628022, -1.3496062 , -0.08037287,  1.16731536],
       [-1.03367032,  0.19508381, -0.11777636, -0.03335187],
       [-0.68968668, -2.59114164, -0.15268033, -1.23401909],
       [-1.2219853 , -2.0519077 , -0.25289545,  1.16731536],
       [-0.81274405, -1.42555047, -0.34034534, -1.23401909],
       [-1.0316481 , -0.11784035, -0.3591171 , -1.23401909],
       [-1.05088134, -1.36198577, -0.43003381, -0.03335187],
       [-1.14581818, -0.93990057, -0.57033117, -1.23401909],
       [-1.32745787,  0.20707435, -1.52838812,  1.16731536],
       [-1.17848774,  1.21546693, -1.5897171 , -1.23401909],
       [-1.65133124,  0.08833235, -1.8148695 ,  1.16731536],
       [-1.6442929 , -0.21821836,  0.6999006 , -0.03335187],
       [-1.673664  ,  0.50288031, -1.83108825, -1.23401909],
       [-1.66156131, -2.57422677, -1.83108825,  1.16731536],
       [-1.673664  , -0.17528531, -1.4462786 , -1.23401909],
       [ 0.57410176, -1.10165542,  0.29637694, -1.23401909],
       [ 0.4220906 ,  0.20479752,  0.29718526, -0.03335187],
       [ 0.38030758,  0.50538623,  0.32125438, -1.23401909],
       [ 1.00438367,  1.27949493,  0.35403374, -0.03335187],
       [ 0.88337621,  0.03184527,  0.39886959,  1.16731536],
       [ 0.06818346, -0.00563469,  0.42076085, -1.23401909],
       [ 0.43980557,  0.8577414 ,  0.57603938,  1.16731536],
       [ 0.37487683, -0.27853767,  0.68120328, -0.03335187],
       [ 0.25588265,  1.16795814, -1.83108825,  1.16731536],
       [ 0.02890359, -0.28988105,  0.71310446, -1.23401909],
       [ 0.07658668,  1.1774935 ,  0.72224334,  1.16731536],
       [-0.02154122,  0.03794589,  0.75275659, -0.03335187],
       [-0.165823  , -0.58832162,  0.76510399, -0.03335187],
       [ 0.04654576, -0.82621636, -0.63359259,  1.16731536],
       [-0.22985461,  0.65460485, -0.6558447 , -1.23401909],
       [ 0.00825076,  0.82311815, -0.68917401, -0.03335187],
       [-0.06367255,  0.224807  ,  1.177531  ,  1.16731536],
       [-0.19889043,  2.23914065, -0.82463513, -0.03335187],
       [-0.20884945,  1.15023284, -0.918423  ,  1.16731536],
       [-0.2894745 , -0.22465065, -1.05478086,  1.16731536],
       [-1.2219853 ,  1.13809338, -1.07959552,  1.16731536],
       [-0.25789476,  0.27463345, -1.43850805, -1.23401909],
       [-0.4346159 , -0.68736485, -0.00270767, -0.03335187],
       [-0.63708012,  1.32165249, -0.03539459,  1.16731536],
       [-1.2219853 , -1.3496062 , -0.08037287,  1.16731536],
       [-1.03367032,  0.19508381, -0.11777636, -0.03335187],
       [-0.68968668, -2.59114164, -0.15268033, -1.23401909],
       [-1.2219853 , -2.0519077 , -0.25289545,  1.16731536],
       [-0.81274405, -1.42555047, -0.34034534, -1.23401909],
       [-1.0316481 , -0.11784035, -0.3591171 , -1.23401909],
       [-1.05088134, -1.36198577, -0.43003381,  1.16731536],
       [-1.14581818, -0.93990057, -0.57033117, -1.23401909],
       [-1.2219853 ,  0.20707435, -1.52838812,  1.16731536],
       [-1.17848774,  1.21546693, -1.5897171 , -1.23401909],
       [-1.65133124,  0.08833235, -1.8148695 ,  1.16731536],
       [-1.6442929 , -0.21821836,  0.6999006 , -0.03335187],
       [-1.673664  ,  0.50288031, -1.83108825, -1.23401909],
       [-1.66156131, -2.57422677, -1.83108825,  1.16731536],
       [-1.673664  , -0.17528531, -1.4462786 , -1.23401909],
       [ 2.01819092,  0.55696553,  2.18783528,  1.16731536],
       [ 1.95675646,  1.0893969 ,  1.95029024, -1.23401909],
       [ 1.75232048, -0.75766814,  1.64392865, -0.03335187],
       [ 1.54982902, -0.1132146 ,  1.43322263,  1.16731536],
       [ 1.49925539, -1.11632102,  1.28814125, -0.03335187],
       [ 1.27083396, -0.806604  ,  1.25996984,  1.16731536],
       [ 1.3319795 ,  0.93574262, -0.74312422, -1.23401909],
       [ 1.23558377,  0.87437939,  0.92787631, -0.03335187],
       [ 1.01776417,  0.99163696,  0.82340982,  1.16731536],
       [ 1.08011094, -0.48065199,  0.76691751, -1.23401909],
       [ 0.60181303, -0.4102384 ,  0.1210342 , -0.03335187],
       [ 0.57410176, -1.10165542,  0.29637694, -1.23401909],
       [ 0.4220906 ,  0.20479752,  0.29718526, -0.03335187],
       [ 0.38030758,  0.50538623,  0.32125438, -1.23401909],
       [ 1.00438367,  1.27949493,  0.35403374, -0.03335187],
       [ 0.88337621,  0.03184527,  0.39886959,  1.16731536],
       [ 0.06818346, -0.00563469,  0.42076085, -1.23401909],
       [ 0.43980557,  0.8577414 ,  0.57603938,  1.16731536],
       [ 0.37487683, -0.27853767,  0.68120328, -0.03335187]])

In [10]:
x=pd.DataFrame(x,columns=names)
x.head()
#Now again we convert it into dataframe from scale

   R&D Spend  Administration  Marketing Spend     State
0   2.018191        0.556966         2.187835  1.167315
1   1.956756        1.089397         1.950290 -1.234019
2   1.752320       -0.757668         1.643929 -0.033352
3   1.549829       -0.113215         1.433223  1.167315
4   1.499255       -1.116321         1.288141 -0.033352

Now we are going to create a model by using train test and spilt

In [11]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train

     R&D Spend  Administration  Marketing Spend     State
62   -0.165823       -0.588322         0.765104 -0.033352
67   -0.198890        2.239141        -0.824635 -0.033352
32   -0.257895        0.274633        -1.438508 -1.234019
65    0.008251        0.823118        -0.689174 -0.033352
10    0.601813       -0.410238         0.121034 -0.033352
..         ...             ...              ...       ...
64   -0.229855        0.654605        -0.655845 -1.234019
24    0.046546       -0.826216        -0.633593  1.167315
56    0.439806        0.857741         0.576039  1.167315
104   0.883376        0.031845         0.398870  1.167315
0     2.018191        0.556966         2.187835  1.167315

[86 rows x 4 columns]

#ANN Creation

For deep learning model we have certain libraries

1.TensorFlow

2.Keras

In [12]:
# We are going to use TensorFlow model
import tensorflow
# here we are using the sequential model like [input->hidden layers->output this kind is known as sequential mode]

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
model = Sequential()
# In this model we need to create layers using Dense

#Creating the input layer

(here we are taking the four layers so units is 4)

In [15]:
# Input layer - By using Dense
# Weights - By using kernel_initializer
# Activation function - relu (Positive means  positive if it is negative means Zero)

model.add(Dense(units = 4,kernel_initializer= "random_uniform",activation= "relu"))

# Creating the hidden layers 

(Here there is no restriction for the hidden layer so randomly we are taking the 10 hidden layers)

In [16]:
# Hidden layer units is 10
# kernela and activation are same as input if we want we will change.

# First hidden layer
model.add(Dense(units = 10,kernel_initializer= "random_uniform",activation= "relu"))

In [17]:
#  Second hidden layer
model.add(Dense(units = 12,kernel_initializer= "random_uniform",activation= "relu"))

#The third stage is output layer

here we are using the regression so there is no need for the multiple units only ine unit is enough

In [18]:
# We dont need any activation madel in output layer
model.add(Dense(units = 1 ,kernel_initializer= "random_uniform"))

#Then we need to do compile the output by using the mean square error (mse)

In [19]:
model.compile(loss="mse",metrics=["mse"],optimizer="adam")

After compile we need to train the data for that we need to fit it.

In [20]:
model.fit(x_train,y_train,epochs=10,batch_size=10)
#epochs means one forward mevement and one backward movement is called as epochs.like it is used for the calculating error

Epoch 1/10
9/9 [==============================] - 1s 4ms/step - loss: 13240040448.0000 - mse: 13240040448.0000
Epoch 2/10
9/9 [==============================] - 0s 13ms/step - loss: 13240038400.0000 - mse: 13240038400.0000
Epoch 3/10
9/9 [==============================] - 0s 9ms/step - loss: 13240034304.0000 - mse: 13240034304.0000
Epoch 4/10
9/9 [==============================] - 0s 3ms/step - loss: 13240031232.0000 - mse: 13240031232.0000
Epoch 5/10
9/9 [==============================] - 0s 6ms/step - loss: 13240025088.0000 - mse: 13240026112.0000
Epoch 6/10
9/9 [==============================] - 0s 3ms/step - loss: 13240018944.0000 - mse: 13240018944.0000
Epoch 7/10
9/9 [==============================] - 0s 3ms/step - loss: 13240007680.0000 - mse: 13240007680.0000
Epoch 8/10
9/9 [==============================] - 0s 3ms/step - loss: 13239994368.0000 - mse: 13239994368.0000
Epoch 9/10
9/9 [==============================] - 0s 3ms/step - loss: 13239974912.0000 - mse: 13239974912.0000
Epoch 10/10
9/9 [==============================] - 0s 3ms/step - loss: 13239948288.0000 - mse: 13239948288.0000

Now we want to predict the values

In [21]:
pred = model.predict(x_test)
pred
#this is our predicted value

# then we need to compare the original value and predicted value

array([[0.66431403],
       [0.37696812],
       [0.37696812],
       [0.52935404],
       [0.70825696],
       [0.40878752],
       [0.4957961 ],
       [0.7162679 ],
       [0.37696812],
       [0.4802977 ],
       [0.66675675],
       [0.63206995],
       [0.66431403],
       [0.4957961 ],
       [0.73188823],
       [0.45082495],
       [0.6135547 ],
       [0.40116915],
       [0.40116915],
       [0.5496225 ],
       [0.37696812],
       [0.49069425]], dtype=float32)

#For comparision we need to use the inbuild module metrices

In [22]:
from sklearn import metrics
metrics.mean_squared_error(pred,y_test)
# This is not a optimal model because there is more errors are there

18904125731.501472

For this we need to change the epochs and add the new layers in the hidden layers